### PR TITLE
I think I found a typo and suggest a clarification.

### PR DESCRIPTION
**Pull request by elvey**
A typo and a suggested clarification:

s/DNSEY/DNSKEY/. 
Add commas to line 347.

### CODE REVIEW

**Comment by elvey** [comment]
Hello?  Please review.

**Review by dblacka — APPROVED** [review]
these tiny changes look correct to me

**Comment by shuque** [comment]
Looks good to me too.

@elvey - since we've renamed the draft to draft-ietf-dnsop-multi-provider-dnssec.xml after the IETF dnsop working group formally adopted this work, I'm not sure how to merge your commit to the older file, other than manually doing your changes to the new file. Would you mind re-issuing your PR against the new file? That way, your username will be credited with the commit. Thanks!

**Comment by elvey** [comment]
I noticed shuque applied my commit the day he commented - with https://github.com/shuque/multi-provider-dnssec/commit/38dbe2732b84d87c6cff3fa290f62b5c6066270a ("Fix typo and nit - from @elvey")  I presume I can't re-issue my PR against the new file since it already has the changes, so I'm closing this.  Good enough.  Glad the change is in.

**Pull request closed without merging**
